################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../bcl_test_release/bcl/example/score/example_score.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_assignment_blast_profile.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_assignment_blosum.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_assignment_identity.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_assignment_pam.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_assignment_phat.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_assignment_property.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_assignment_ss_prediction.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_neighborhood_distances.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_neighborhood_exposure.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_neighborhood_exposure_prediction.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_pair_atom_clash.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_pair_clash.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_pair_contact.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_pair_contact_energy.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_pair_distance.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_pair_distance_fitted_function.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_pair_distance_smooth.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_pair_hi_res_clash.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_pair_sidechain_interaction.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_sequence.cpp \
../bcl_test_release/bcl/example/score/example_score_aa_sequence_pair.cpp \
../bcl_test_release/bcl/example/score/example_score_accessibility.cpp \
../bcl_test_release/bcl/example/score/example_score_accessibility_hydrophobic_moment.cpp \
../bcl_test_release/bcl/example/score/example_score_accessibility_hydrophobic_moment_magnitude.cpp \
../bcl_test_release/bcl/example/score/example_score_alignment_assignment.cpp \
../bcl_test_release/bcl/example/score/example_score_alignment_gap.cpp \
../bcl_test_release/bcl/example/score/example_score_alignment_quality.cpp \
../bcl_test_release/bcl/example/score/example_score_assignment.cpp \
../bcl_test_release/bcl/example/score/example_score_assignment_gap_simple.cpp \
../bcl_test_release/bcl/example/score/example_score_body_assignment.cpp \
../bcl_test_release/bcl/example/score/example_score_body_connectivity_density.cpp \
../bcl_test_release/bcl/example/score/example_score_body_extent_agreement.cpp \
../bcl_test_release/bcl/example/score/example_score_body_extent_position_agreement.cpp \
../bcl_test_release/bcl/example/score/example_score_consensus_enrichment.cpp \
../bcl_test_release/bcl/example/score/example_score_contact_order.cpp \
../bcl_test_release/bcl/example/score/example_score_data_set_pairwise_bipolar.cpp \
../bcl_test_release/bcl/example/score/example_score_data_set_pairwise_coordinate_exclusion.cpp \
../bcl_test_release/bcl/example/score/example_score_data_set_pairwise_coordinate_triangulation.cpp \
../bcl_test_release/bcl/example/score/example_score_data_set_pairwise_data_density.cpp \
../bcl_test_release/bcl/example/score/example_score_data_set_pairwise_distance_change_magnitude.cpp \
../bcl_test_release/bcl/example/score/example_score_data_set_pairwise_euclidian_distance.cpp \
../bcl_test_release/bcl/example/score/example_score_data_set_pairwise_residue_type_exclusion.cpp \
../bcl_test_release/bcl/example/score/example_score_data_set_pairwise_sequence_separation.cpp \
../bcl_test_release/bcl/example/score/example_score_data_set_pairwise_size.cpp \
../bcl_test_release/bcl/example/score/example_score_data_set_pairwise_sse_center.cpp \
../bcl_test_release/bcl/example/score/example_score_data_set_pairwise_sse_connection.cpp \
../bcl_test_release/bcl/example/score/example_score_data_set_pairwise_sse_size.cpp \
../bcl_test_release/bcl/example/score/example_score_data_set_pairwise_sse_term.cpp \
../bcl_test_release/bcl/example/score/example_score_data_set_pairwise_structural_exposure.cpp \
../bcl_test_release/bcl/example/score/example_score_density_profile_sse_agreement.cpp \
../bcl_test_release/bcl/example/score/example_score_energy_distribution.cpp \
../bcl_test_release/bcl/example/score/example_score_environment_predictions.cpp \
../bcl_test_release/bcl/example/score/example_score_epr_accessibility.cpp \
../bcl_test_release/bcl/example/score/example_score_fuzzy_logic_filter.cpp \
../bcl_test_release/bcl/example/score/example_score_log_normal_distribution.cpp \
../bcl_test_release/bcl/example/score/example_score_loop.cpp \
../bcl_test_release/bcl/example/score/example_score_loop_closure.cpp \
../bcl_test_release/bcl/example/score/example_score_phi_psi.cpp \
../bcl_test_release/bcl/example/score/example_score_phi_psi_with_sspred.cpp \
../bcl_test_release/bcl/example/score/example_score_pofr.cpp \
../bcl_test_release/bcl/example/score/example_score_protein_atom_density.cpp \
../bcl_test_release/bcl/example/score/example_score_protein_model_aa_neighborhood.cpp \
../bcl_test_release/bcl/example/score/example_score_protein_model_completeness.cpp \
../bcl_test_release/bcl/example/score/example_score_protein_model_defined_loops.cpp \
../bcl_test_release/bcl/example/score/example_score_protein_model_gap.cpp \
../bcl_test_release/bcl/example/score/example_score_protein_model_inverted.cpp \
../bcl_test_release/bcl/example/score/example_score_protein_model_loop_domain_closure.cpp \
../bcl_test_release/bcl/example/score/example_score_protein_model_membrane_topology.cpp \
../bcl_test_release/bcl/example/score/example_score_protein_model_score_sum.cpp \
../bcl_test_release/bcl/example/score/example_score_protein_model_sse.cpp \
../bcl_test_release/bcl/example/score/example_score_protein_model_sse_chirality.cpp \
../bcl_test_release/bcl/example/score/example_score_protein_model_sse_completeness.cpp \
../bcl_test_release/bcl/example/score/example_score_protein_model_sse_linear_loop_proximity.cpp \
../bcl_test_release/bcl/example/score/example_score_protein_model_sse_packing.cpp \
../bcl_test_release/bcl/example/score/example_score_protein_model_sse_pairs.cpp \
../bcl_test_release/bcl/example/score/example_score_radius_of_gyration.cpp \
../bcl_test_release/bcl/example/score/example_score_read_histograms.cpp \
../bcl_test_release/bcl/example/score/example_score_residual_dipolar_coupling_histogram.cpp \
../bcl_test_release/bcl/example/score/example_score_residual_dipolar_coupling_q_value.cpp \
../bcl_test_release/bcl/example/score/example_score_restraint_atom_attraction.cpp \
../bcl_test_release/bcl/example/score/example_score_restraint_atom_distance.cpp \
../bcl_test_release/bcl/example/score/example_score_restraint_body_protein_model.cpp \
../bcl_test_release/bcl/example/score/example_score_restraint_distance_epr.cpp \
../bcl_test_release/bcl/example/score/example_score_restraint_distance_spin_label.cpp \
../bcl_test_release/bcl/example/score/example_score_restraint_energy_well.cpp \
../bcl_test_release/bcl/example/score/example_score_restraint_noe_attraction.cpp \
../bcl_test_release/bcl/example/score/example_score_restraint_noe_knowledge_based.cpp \
../bcl_test_release/bcl/example/score/example_score_restraint_residual_dipolar_coupling.cpp \
../bcl_test_release/bcl/example/score/example_score_restraint_saxs.cpp \
../bcl_test_release/bcl/example/score/example_score_restraint_xlink.cpp \
../bcl_test_release/bcl/example/score/example_score_saxs_type.cpp \
../bcl_test_release/bcl/example/score/example_score_scores.cpp \
../bcl_test_release/bcl/example/score/example_score_slicelist_benchmark.cpp \
../bcl_test_release/bcl/example/score/example_score_sse_membrane_alignment.cpp \
../bcl_test_release/bcl/example/score/example_score_sse_pair_angle_distance.cpp \
../bcl_test_release/bcl/example/score/example_score_sse_pair_connectivity.cpp \
../bcl_test_release/bcl/example/score/example_score_sse_pair_contact.cpp \
../bcl_test_release/bcl/example/score/example_score_sse_pair_packing.cpp \
../bcl_test_release/bcl/example/score/example_score_sse_pool_sses.cpp \
../bcl_test_release/bcl/example/score/example_score_sse_predictions.cpp \
../bcl_test_release/bcl/example/score/example_score_strand_pairing.cpp 

OBJS += \
./bcl_test_release/bcl/example/score/example_score.o \
./bcl_test_release/bcl/example/score/example_score_aa_assignment_blast_profile.o \
./bcl_test_release/bcl/example/score/example_score_aa_assignment_blosum.o \
./bcl_test_release/bcl/example/score/example_score_aa_assignment_identity.o \
./bcl_test_release/bcl/example/score/example_score_aa_assignment_pam.o \
./bcl_test_release/bcl/example/score/example_score_aa_assignment_phat.o \
./bcl_test_release/bcl/example/score/example_score_aa_assignment_property.o \
./bcl_test_release/bcl/example/score/example_score_aa_assignment_ss_prediction.o \
./bcl_test_release/bcl/example/score/example_score_aa_neighborhood_distances.o \
./bcl_test_release/bcl/example/score/example_score_aa_neighborhood_exposure.o \
./bcl_test_release/bcl/example/score/example_score_aa_neighborhood_exposure_prediction.o \
./bcl_test_release/bcl/example/score/example_score_aa_pair_atom_clash.o \
./bcl_test_release/bcl/example/score/example_score_aa_pair_clash.o \
./bcl_test_release/bcl/example/score/example_score_aa_pair_contact.o \
./bcl_test_release/bcl/example/score/example_score_aa_pair_contact_energy.o \
./bcl_test_release/bcl/example/score/example_score_aa_pair_distance.o \
./bcl_test_release/bcl/example/score/example_score_aa_pair_distance_fitted_function.o \
./bcl_test_release/bcl/example/score/example_score_aa_pair_distance_smooth.o \
./bcl_test_release/bcl/example/score/example_score_aa_pair_hi_res_clash.o \
./bcl_test_release/bcl/example/score/example_score_aa_pair_sidechain_interaction.o \
./bcl_test_release/bcl/example/score/example_score_aa_sequence.o \
./bcl_test_release/bcl/example/score/example_score_aa_sequence_pair.o \
./bcl_test_release/bcl/example/score/example_score_accessibility.o \
./bcl_test_release/bcl/example/score/example_score_accessibility_hydrophobic_moment.o \
./bcl_test_release/bcl/example/score/example_score_accessibility_hydrophobic_moment_magnitude.o \
./bcl_test_release/bcl/example/score/example_score_alignment_assignment.o \
./bcl_test_release/bcl/example/score/example_score_alignment_gap.o \
./bcl_test_release/bcl/example/score/example_score_alignment_quality.o \
./bcl_test_release/bcl/example/score/example_score_assignment.o \
./bcl_test_release/bcl/example/score/example_score_assignment_gap_simple.o \
./bcl_test_release/bcl/example/score/example_score_body_assignment.o \
./bcl_test_release/bcl/example/score/example_score_body_connectivity_density.o \
./bcl_test_release/bcl/example/score/example_score_body_extent_agreement.o \
./bcl_test_release/bcl/example/score/example_score_body_extent_position_agreement.o \
./bcl_test_release/bcl/example/score/example_score_consensus_enrichment.o \
./bcl_test_release/bcl/example/score/example_score_contact_order.o \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_bipolar.o \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_coordinate_exclusion.o \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_coordinate_triangulation.o \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_data_density.o \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_distance_change_magnitude.o \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_euclidian_distance.o \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_residue_type_exclusion.o \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_sequence_separation.o \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_size.o \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_sse_center.o \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_sse_connection.o \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_sse_size.o \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_sse_term.o \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_structural_exposure.o \
./bcl_test_release/bcl/example/score/example_score_density_profile_sse_agreement.o \
./bcl_test_release/bcl/example/score/example_score_energy_distribution.o \
./bcl_test_release/bcl/example/score/example_score_environment_predictions.o \
./bcl_test_release/bcl/example/score/example_score_epr_accessibility.o \
./bcl_test_release/bcl/example/score/example_score_fuzzy_logic_filter.o \
./bcl_test_release/bcl/example/score/example_score_log_normal_distribution.o \
./bcl_test_release/bcl/example/score/example_score_loop.o \
./bcl_test_release/bcl/example/score/example_score_loop_closure.o \
./bcl_test_release/bcl/example/score/example_score_phi_psi.o \
./bcl_test_release/bcl/example/score/example_score_phi_psi_with_sspred.o \
./bcl_test_release/bcl/example/score/example_score_pofr.o \
./bcl_test_release/bcl/example/score/example_score_protein_atom_density.o \
./bcl_test_release/bcl/example/score/example_score_protein_model_aa_neighborhood.o \
./bcl_test_release/bcl/example/score/example_score_protein_model_completeness.o \
./bcl_test_release/bcl/example/score/example_score_protein_model_defined_loops.o \
./bcl_test_release/bcl/example/score/example_score_protein_model_gap.o \
./bcl_test_release/bcl/example/score/example_score_protein_model_inverted.o \
./bcl_test_release/bcl/example/score/example_score_protein_model_loop_domain_closure.o \
./bcl_test_release/bcl/example/score/example_score_protein_model_membrane_topology.o \
./bcl_test_release/bcl/example/score/example_score_protein_model_score_sum.o \
./bcl_test_release/bcl/example/score/example_score_protein_model_sse.o \
./bcl_test_release/bcl/example/score/example_score_protein_model_sse_chirality.o \
./bcl_test_release/bcl/example/score/example_score_protein_model_sse_completeness.o \
./bcl_test_release/bcl/example/score/example_score_protein_model_sse_linear_loop_proximity.o \
./bcl_test_release/bcl/example/score/example_score_protein_model_sse_packing.o \
./bcl_test_release/bcl/example/score/example_score_protein_model_sse_pairs.o \
./bcl_test_release/bcl/example/score/example_score_radius_of_gyration.o \
./bcl_test_release/bcl/example/score/example_score_read_histograms.o \
./bcl_test_release/bcl/example/score/example_score_residual_dipolar_coupling_histogram.o \
./bcl_test_release/bcl/example/score/example_score_residual_dipolar_coupling_q_value.o \
./bcl_test_release/bcl/example/score/example_score_restraint_atom_attraction.o \
./bcl_test_release/bcl/example/score/example_score_restraint_atom_distance.o \
./bcl_test_release/bcl/example/score/example_score_restraint_body_protein_model.o \
./bcl_test_release/bcl/example/score/example_score_restraint_distance_epr.o \
./bcl_test_release/bcl/example/score/example_score_restraint_distance_spin_label.o \
./bcl_test_release/bcl/example/score/example_score_restraint_energy_well.o \
./bcl_test_release/bcl/example/score/example_score_restraint_noe_attraction.o \
./bcl_test_release/bcl/example/score/example_score_restraint_noe_knowledge_based.o \
./bcl_test_release/bcl/example/score/example_score_restraint_residual_dipolar_coupling.o \
./bcl_test_release/bcl/example/score/example_score_restraint_saxs.o \
./bcl_test_release/bcl/example/score/example_score_restraint_xlink.o \
./bcl_test_release/bcl/example/score/example_score_saxs_type.o \
./bcl_test_release/bcl/example/score/example_score_scores.o \
./bcl_test_release/bcl/example/score/example_score_slicelist_benchmark.o \
./bcl_test_release/bcl/example/score/example_score_sse_membrane_alignment.o \
./bcl_test_release/bcl/example/score/example_score_sse_pair_angle_distance.o \
./bcl_test_release/bcl/example/score/example_score_sse_pair_connectivity.o \
./bcl_test_release/bcl/example/score/example_score_sse_pair_contact.o \
./bcl_test_release/bcl/example/score/example_score_sse_pair_packing.o \
./bcl_test_release/bcl/example/score/example_score_sse_pool_sses.o \
./bcl_test_release/bcl/example/score/example_score_sse_predictions.o \
./bcl_test_release/bcl/example/score/example_score_strand_pairing.o 

CPP_DEPS += \
./bcl_test_release/bcl/example/score/example_score.d \
./bcl_test_release/bcl/example/score/example_score_aa_assignment_blast_profile.d \
./bcl_test_release/bcl/example/score/example_score_aa_assignment_blosum.d \
./bcl_test_release/bcl/example/score/example_score_aa_assignment_identity.d \
./bcl_test_release/bcl/example/score/example_score_aa_assignment_pam.d \
./bcl_test_release/bcl/example/score/example_score_aa_assignment_phat.d \
./bcl_test_release/bcl/example/score/example_score_aa_assignment_property.d \
./bcl_test_release/bcl/example/score/example_score_aa_assignment_ss_prediction.d \
./bcl_test_release/bcl/example/score/example_score_aa_neighborhood_distances.d \
./bcl_test_release/bcl/example/score/example_score_aa_neighborhood_exposure.d \
./bcl_test_release/bcl/example/score/example_score_aa_neighborhood_exposure_prediction.d \
./bcl_test_release/bcl/example/score/example_score_aa_pair_atom_clash.d \
./bcl_test_release/bcl/example/score/example_score_aa_pair_clash.d \
./bcl_test_release/bcl/example/score/example_score_aa_pair_contact.d \
./bcl_test_release/bcl/example/score/example_score_aa_pair_contact_energy.d \
./bcl_test_release/bcl/example/score/example_score_aa_pair_distance.d \
./bcl_test_release/bcl/example/score/example_score_aa_pair_distance_fitted_function.d \
./bcl_test_release/bcl/example/score/example_score_aa_pair_distance_smooth.d \
./bcl_test_release/bcl/example/score/example_score_aa_pair_hi_res_clash.d \
./bcl_test_release/bcl/example/score/example_score_aa_pair_sidechain_interaction.d \
./bcl_test_release/bcl/example/score/example_score_aa_sequence.d \
./bcl_test_release/bcl/example/score/example_score_aa_sequence_pair.d \
./bcl_test_release/bcl/example/score/example_score_accessibility.d \
./bcl_test_release/bcl/example/score/example_score_accessibility_hydrophobic_moment.d \
./bcl_test_release/bcl/example/score/example_score_accessibility_hydrophobic_moment_magnitude.d \
./bcl_test_release/bcl/example/score/example_score_alignment_assignment.d \
./bcl_test_release/bcl/example/score/example_score_alignment_gap.d \
./bcl_test_release/bcl/example/score/example_score_alignment_quality.d \
./bcl_test_release/bcl/example/score/example_score_assignment.d \
./bcl_test_release/bcl/example/score/example_score_assignment_gap_simple.d \
./bcl_test_release/bcl/example/score/example_score_body_assignment.d \
./bcl_test_release/bcl/example/score/example_score_body_connectivity_density.d \
./bcl_test_release/bcl/example/score/example_score_body_extent_agreement.d \
./bcl_test_release/bcl/example/score/example_score_body_extent_position_agreement.d \
./bcl_test_release/bcl/example/score/example_score_consensus_enrichment.d \
./bcl_test_release/bcl/example/score/example_score_contact_order.d \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_bipolar.d \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_coordinate_exclusion.d \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_coordinate_triangulation.d \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_data_density.d \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_distance_change_magnitude.d \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_euclidian_distance.d \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_residue_type_exclusion.d \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_sequence_separation.d \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_size.d \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_sse_center.d \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_sse_connection.d \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_sse_size.d \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_sse_term.d \
./bcl_test_release/bcl/example/score/example_score_data_set_pairwise_structural_exposure.d \
./bcl_test_release/bcl/example/score/example_score_density_profile_sse_agreement.d \
./bcl_test_release/bcl/example/score/example_score_energy_distribution.d \
./bcl_test_release/bcl/example/score/example_score_environment_predictions.d \
./bcl_test_release/bcl/example/score/example_score_epr_accessibility.d \
./bcl_test_release/bcl/example/score/example_score_fuzzy_logic_filter.d \
./bcl_test_release/bcl/example/score/example_score_log_normal_distribution.d \
./bcl_test_release/bcl/example/score/example_score_loop.d \
./bcl_test_release/bcl/example/score/example_score_loop_closure.d \
./bcl_test_release/bcl/example/score/example_score_phi_psi.d \
./bcl_test_release/bcl/example/score/example_score_phi_psi_with_sspred.d \
./bcl_test_release/bcl/example/score/example_score_pofr.d \
./bcl_test_release/bcl/example/score/example_score_protein_atom_density.d \
./bcl_test_release/bcl/example/score/example_score_protein_model_aa_neighborhood.d \
./bcl_test_release/bcl/example/score/example_score_protein_model_completeness.d \
./bcl_test_release/bcl/example/score/example_score_protein_model_defined_loops.d \
./bcl_test_release/bcl/example/score/example_score_protein_model_gap.d \
./bcl_test_release/bcl/example/score/example_score_protein_model_inverted.d \
./bcl_test_release/bcl/example/score/example_score_protein_model_loop_domain_closure.d \
./bcl_test_release/bcl/example/score/example_score_protein_model_membrane_topology.d \
./bcl_test_release/bcl/example/score/example_score_protein_model_score_sum.d \
./bcl_test_release/bcl/example/score/example_score_protein_model_sse.d \
./bcl_test_release/bcl/example/score/example_score_protein_model_sse_chirality.d \
./bcl_test_release/bcl/example/score/example_score_protein_model_sse_completeness.d \
./bcl_test_release/bcl/example/score/example_score_protein_model_sse_linear_loop_proximity.d \
./bcl_test_release/bcl/example/score/example_score_protein_model_sse_packing.d \
./bcl_test_release/bcl/example/score/example_score_protein_model_sse_pairs.d \
./bcl_test_release/bcl/example/score/example_score_radius_of_gyration.d \
./bcl_test_release/bcl/example/score/example_score_read_histograms.d \
./bcl_test_release/bcl/example/score/example_score_residual_dipolar_coupling_histogram.d \
./bcl_test_release/bcl/example/score/example_score_residual_dipolar_coupling_q_value.d \
./bcl_test_release/bcl/example/score/example_score_restraint_atom_attraction.d \
./bcl_test_release/bcl/example/score/example_score_restraint_atom_distance.d \
./bcl_test_release/bcl/example/score/example_score_restraint_body_protein_model.d \
./bcl_test_release/bcl/example/score/example_score_restraint_distance_epr.d \
./bcl_test_release/bcl/example/score/example_score_restraint_distance_spin_label.d \
./bcl_test_release/bcl/example/score/example_score_restraint_energy_well.d \
./bcl_test_release/bcl/example/score/example_score_restraint_noe_attraction.d \
./bcl_test_release/bcl/example/score/example_score_restraint_noe_knowledge_based.d \
./bcl_test_release/bcl/example/score/example_score_restraint_residual_dipolar_coupling.d \
./bcl_test_release/bcl/example/score/example_score_restraint_saxs.d \
./bcl_test_release/bcl/example/score/example_score_restraint_xlink.d \
./bcl_test_release/bcl/example/score/example_score_saxs_type.d \
./bcl_test_release/bcl/example/score/example_score_scores.d \
./bcl_test_release/bcl/example/score/example_score_slicelist_benchmark.d \
./bcl_test_release/bcl/example/score/example_score_sse_membrane_alignment.d \
./bcl_test_release/bcl/example/score/example_score_sse_pair_angle_distance.d \
./bcl_test_release/bcl/example/score/example_score_sse_pair_connectivity.d \
./bcl_test_release/bcl/example/score/example_score_sse_pair_contact.d \
./bcl_test_release/bcl/example/score/example_score_sse_pair_packing.d \
./bcl_test_release/bcl/example/score/example_score_sse_pool_sses.d \
./bcl_test_release/bcl/example/score/example_score_sse_predictions.d \
./bcl_test_release/bcl/example/score/example_score_strand_pairing.d 


# Each subdirectory must supply rules for building sources it contributes
bcl_test_release/bcl/example/score/%.o: ../bcl_test_release/bcl/example/score/%.cpp bcl_test_release/bcl/example/score/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	distcc g++ -I../include -I../example -I../apps -I../extern/noarch/mysql/5.1.48/include -I../extern/noarch/mysqlpp/3.1.0/include -I../extern/noarch/bzip2/1.0.5/include -I../extern/noarch/zlib/1.2.5/include -I../extern/noarch/ati/2.5/include -O2 -Wall -c -fmessage-length=0 -Wno-deprecated -fno-pretty-templates -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


