################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../example/chemistry/example_chemistry.cpp \
../example/chemistry/example_chemistry_aa_fragment_complete.cpp \
../example/chemistry/example_chemistry_atom_clash_score.cpp \
../example/chemistry/example_chemistry_atom_complete.cpp \
../example/chemistry/example_chemistry_atom_configurational_shared.cpp \
../example/chemistry/example_chemistry_atom_conformational_shared.cpp \
../example/chemistry/example_chemistry_atom_constitutional_shared.cpp \
../example/chemistry/example_chemistry_atom_environment.cpp \
../example/chemistry/example_chemistry_atom_environment_bender.cpp \
../example/chemistry/example_chemistry_atom_one_four_interaction_score.cpp \
../example/chemistry/example_chemistry_atom_type_data.cpp \
../example/chemistry/example_chemistry_atom_types.cpp \
../example/chemistry/example_chemistry_atom_vdw_score.cpp \
../example/chemistry/example_chemistry_atom_vector.cpp \
../example/chemistry/example_chemistry_bond_configurational.cpp \
../example/chemistry/example_chemistry_bond_conformational.cpp \
../example/chemistry/example_chemistry_bond_constitutional.cpp \
../example/chemistry/example_chemistry_bond_isometry_handler.cpp \
../example/chemistry/example_chemistry_bond_lengths.cpp \
../example/chemistry/example_chemistry_collector_valence.cpp \
../example/chemistry/example_chemistry_configuration_graph_converter.cpp \
../example/chemistry/example_chemistry_configuration_set.cpp \
../example/chemistry/example_chemistry_configuration_set_same_constitution.cpp \
../example/chemistry/example_chemistry_configurational_bond_type_data.cpp \
../example/chemistry/example_chemistry_configurational_bond_types.cpp \
../example/chemistry/example_chemistry_conformation_comparison_by_dihedral_bins.cpp \
../example/chemistry/example_chemistry_conformation_comparison_by_dihedrals.cpp \
../example/chemistry/example_chemistry_conformation_comparison_by_fragments.cpp \
../example/chemistry/example_chemistry_conformation_comparison_by_property.cpp \
../example/chemistry/example_chemistry_conformation_comparison_by_real_space_rmsd.cpp \
../example/chemistry/example_chemistry_conformation_comparison_by_rmsd.cpp \
../example/chemistry/example_chemistry_conformation_comparison_by_substructure.cpp \
../example/chemistry/example_chemistry_conformation_comparison_by_symmetry_rmsd.cpp \
../example/chemistry/example_chemistry_conformation_comparison_property_field_correlation.cpp \
../example/chemistry/example_chemistry_conformation_comparison_property_rmsd_x.cpp \
../example/chemistry/example_chemistry_conformation_comparison_psi_field.cpp \
../example/chemistry/example_chemistry_conformation_comparison_psi_flex_field.cpp \
../example/chemistry/example_chemistry_conformation_graph_converter.cpp \
../example/chemistry/example_chemistry_conformation_set.cpp \
../example/chemistry/example_chemistry_conformation_set_same_configuration.cpp \
../example/chemistry/example_chemistry_conformation_set_same_constitution.cpp \
../example/chemistry/example_chemistry_constitution_graph_converter.cpp \
../example/chemistry/example_chemistry_constitution_set.cpp \
../example/chemistry/example_chemistry_constitutional_bond_type_data.cpp \
../example/chemistry/example_chemistry_constitutional_bond_types.cpp \
../example/chemistry/example_chemistry_coulombic_score.cpp \
../example/chemistry/example_chemistry_cs_code.cpp \
../example/chemistry/example_chemistry_descriptor_to_score_adaptor.cpp \
../example/chemistry/example_chemistry_electron_configuration.cpp \
../example/chemistry/example_chemistry_element_structure_factor.cpp \
../example/chemistry/example_chemistry_element_type_data.cpp \
../example/chemistry/example_chemistry_element_types.cpp \
../example/chemistry/example_chemistry_fragment_alchemy.cpp \
../example/chemistry/example_chemistry_fragment_complete.cpp \
../example/chemistry/example_chemistry_fragment_configuration_shared.cpp \
../example/chemistry/example_chemistry_fragment_conformation_shared.cpp \
../example/chemistry/example_chemistry_fragment_connector.cpp \
../example/chemistry/example_chemistry_fragment_constitution_shared.cpp \
../example/chemistry/example_chemistry_fragment_cyclize.cpp \
../example/chemistry/example_chemistry_fragment_ensemble.cpp \
../example/chemistry/example_chemistry_fragment_feed_from_file.cpp \
../example/chemistry/example_chemistry_fragment_feed_from_stream.cpp \
../example/chemistry/example_chemistry_fragment_graph_marker.cpp \
../example/chemistry/example_chemistry_fragment_grow.cpp \
../example/chemistry/example_chemistry_fragment_molecule.cpp \
../example/chemistry/example_chemistry_fragment_probability_score.cpp \
../example/chemistry/example_chemistry_fragment_remove_bond.cpp \
../example/chemistry/example_chemistry_fragment_ring_swap.cpp \
../example/chemistry/example_chemistry_fragment_split_ecfp_fragments.cpp \
../example/chemistry/example_chemistry_fragment_split_isolate.cpp \
../example/chemistry/example_chemistry_fragment_split_largest_component.cpp \
../example/chemistry/example_chemistry_fragment_split_linear_fragments.cpp \
../example/chemistry/example_chemistry_fragment_split_rigid.cpp \
../example/chemistry/example_chemistry_fragment_split_rings.cpp \
../example/chemistry/example_chemistry_fragment_split_rings_with_unsaturated_substituents.cpp \
../example/chemistry/example_chemistry_fragment_split_scaffolds.cpp \
../example/chemistry/example_chemistry_fragment_split_unbridged_rings.cpp \
../example/chemistry/example_chemistry_fragment_swap_amide.cpp \
../example/chemistry/example_chemistry_has_properties.cpp \
../example/chemistry/example_chemistry_merge_fragment_complete.cpp \
../example/chemistry/example_chemistry_mol_align_by_parts.cpp \
../example/chemistry/example_chemistry_molecular_configuration_shared.cpp \
../example/chemistry/example_chemistry_molecular_conformation_shared.cpp \
../example/chemistry/example_chemistry_molecular_constitution_shared.cpp \
../example/chemistry/example_chemistry_molecule_complete.cpp \
../example/chemistry/example_chemistry_molecule_ensemble.cpp \
../example/chemistry/example_chemistry_molecule_environment.cpp \
../example/chemistry/example_chemistry_molecule_fragment_recombination.cpp \
../example/chemistry/example_chemistry_molecule_storage_file.cpp \
../example/chemistry/example_chemistry_mutate_chirality.cpp \
../example/chemistry/example_chemistry_mutate_fragment.cpp \
../example/chemistry/example_chemistry_pick_atom_random.cpp \
../example/chemistry/example_chemistry_possible_atom_types_for_atom.cpp \
../example/chemistry/example_chemistry_priority_dihedral_angles.cpp \
../example/chemistry/example_chemistry_reaction_complete.cpp \
../example/chemistry/example_chemistry_reaction_ensemble.cpp \
../example/chemistry/example_chemistry_reaction_search.cpp \
../example/chemistry/example_chemistry_reaction_structure.cpp \
../example/chemistry/example_chemistry_reaction_worker.cpp \
../example/chemistry/example_chemistry_rotamer_dihedral_bond_data.cpp \
../example/chemistry/example_chemistry_rotamer_library_file.cpp \
../example/chemistry/example_chemistry_sample_conformations.cpp \
../example/chemistry/example_chemistry_search_fragment_library_from_tree.cpp \
../example/chemistry/example_chemistry_small_molecule_fragment_isomorphism.cpp \
../example/chemistry/example_chemistry_small_molecule_fragment_mapping.cpp \
../example/chemistry/example_chemistry_small_molecule_misc_properties.cpp \
../example/chemistry/example_chemistry_small_molecule_qsar_storage_file.cpp \
../example/chemistry/example_chemistry_small_molecule_string_properties_cached.cpp \
../example/chemistry/example_chemistry_small_molecule_string_properties_mapped.cpp \
../example/chemistry/example_chemistry_small_molecule_string_properties_name.cpp \
../example/chemistry/example_chemistry_small_molecule_string_properties_numeric.cpp \
../example/chemistry/example_chemistry_small_molecule_string_properties_types.cpp \
../example/chemistry/example_chemistry_solvents.cpp \
../example/chemistry/example_chemistry_stereocenters_handler.cpp \
../example/chemistry/example_chemistry_sub_fragment.cpp \
../example/chemistry/example_chemistry_substituent_conformational.cpp 

OBJS += \
./example/chemistry/example_chemistry.o \
./example/chemistry/example_chemistry_aa_fragment_complete.o \
./example/chemistry/example_chemistry_atom_clash_score.o \
./example/chemistry/example_chemistry_atom_complete.o \
./example/chemistry/example_chemistry_atom_configurational_shared.o \
./example/chemistry/example_chemistry_atom_conformational_shared.o \
./example/chemistry/example_chemistry_atom_constitutional_shared.o \
./example/chemistry/example_chemistry_atom_environment.o \
./example/chemistry/example_chemistry_atom_environment_bender.o \
./example/chemistry/example_chemistry_atom_one_four_interaction_score.o \
./example/chemistry/example_chemistry_atom_type_data.o \
./example/chemistry/example_chemistry_atom_types.o \
./example/chemistry/example_chemistry_atom_vdw_score.o \
./example/chemistry/example_chemistry_atom_vector.o \
./example/chemistry/example_chemistry_bond_configurational.o \
./example/chemistry/example_chemistry_bond_conformational.o \
./example/chemistry/example_chemistry_bond_constitutional.o \
./example/chemistry/example_chemistry_bond_isometry_handler.o \
./example/chemistry/example_chemistry_bond_lengths.o \
./example/chemistry/example_chemistry_collector_valence.o \
./example/chemistry/example_chemistry_configuration_graph_converter.o \
./example/chemistry/example_chemistry_configuration_set.o \
./example/chemistry/example_chemistry_configuration_set_same_constitution.o \
./example/chemistry/example_chemistry_configurational_bond_type_data.o \
./example/chemistry/example_chemistry_configurational_bond_types.o \
./example/chemistry/example_chemistry_conformation_comparison_by_dihedral_bins.o \
./example/chemistry/example_chemistry_conformation_comparison_by_dihedrals.o \
./example/chemistry/example_chemistry_conformation_comparison_by_fragments.o \
./example/chemistry/example_chemistry_conformation_comparison_by_property.o \
./example/chemistry/example_chemistry_conformation_comparison_by_real_space_rmsd.o \
./example/chemistry/example_chemistry_conformation_comparison_by_rmsd.o \
./example/chemistry/example_chemistry_conformation_comparison_by_substructure.o \
./example/chemistry/example_chemistry_conformation_comparison_by_symmetry_rmsd.o \
./example/chemistry/example_chemistry_conformation_comparison_property_field_correlation.o \
./example/chemistry/example_chemistry_conformation_comparison_property_rmsd_x.o \
./example/chemistry/example_chemistry_conformation_comparison_psi_field.o \
./example/chemistry/example_chemistry_conformation_comparison_psi_flex_field.o \
./example/chemistry/example_chemistry_conformation_graph_converter.o \
./example/chemistry/example_chemistry_conformation_set.o \
./example/chemistry/example_chemistry_conformation_set_same_configuration.o \
./example/chemistry/example_chemistry_conformation_set_same_constitution.o \
./example/chemistry/example_chemistry_constitution_graph_converter.o \
./example/chemistry/example_chemistry_constitution_set.o \
./example/chemistry/example_chemistry_constitutional_bond_type_data.o \
./example/chemistry/example_chemistry_constitutional_bond_types.o \
./example/chemistry/example_chemistry_coulombic_score.o \
./example/chemistry/example_chemistry_cs_code.o \
./example/chemistry/example_chemistry_descriptor_to_score_adaptor.o \
./example/chemistry/example_chemistry_electron_configuration.o \
./example/chemistry/example_chemistry_element_structure_factor.o \
./example/chemistry/example_chemistry_element_type_data.o \
./example/chemistry/example_chemistry_element_types.o \
./example/chemistry/example_chemistry_fragment_alchemy.o \
./example/chemistry/example_chemistry_fragment_complete.o \
./example/chemistry/example_chemistry_fragment_configuration_shared.o \
./example/chemistry/example_chemistry_fragment_conformation_shared.o \
./example/chemistry/example_chemistry_fragment_connector.o \
./example/chemistry/example_chemistry_fragment_constitution_shared.o \
./example/chemistry/example_chemistry_fragment_cyclize.o \
./example/chemistry/example_chemistry_fragment_ensemble.o \
./example/chemistry/example_chemistry_fragment_feed_from_file.o \
./example/chemistry/example_chemistry_fragment_feed_from_stream.o \
./example/chemistry/example_chemistry_fragment_graph_marker.o \
./example/chemistry/example_chemistry_fragment_grow.o \
./example/chemistry/example_chemistry_fragment_molecule.o \
./example/chemistry/example_chemistry_fragment_probability_score.o \
./example/chemistry/example_chemistry_fragment_remove_bond.o \
./example/chemistry/example_chemistry_fragment_ring_swap.o \
./example/chemistry/example_chemistry_fragment_split_ecfp_fragments.o \
./example/chemistry/example_chemistry_fragment_split_isolate.o \
./example/chemistry/example_chemistry_fragment_split_largest_component.o \
./example/chemistry/example_chemistry_fragment_split_linear_fragments.o \
./example/chemistry/example_chemistry_fragment_split_rigid.o \
./example/chemistry/example_chemistry_fragment_split_rings.o \
./example/chemistry/example_chemistry_fragment_split_rings_with_unsaturated_substituents.o \
./example/chemistry/example_chemistry_fragment_split_scaffolds.o \
./example/chemistry/example_chemistry_fragment_split_unbridged_rings.o \
./example/chemistry/example_chemistry_fragment_swap_amide.o \
./example/chemistry/example_chemistry_has_properties.o \
./example/chemistry/example_chemistry_merge_fragment_complete.o \
./example/chemistry/example_chemistry_mol_align_by_parts.o \
./example/chemistry/example_chemistry_molecular_configuration_shared.o \
./example/chemistry/example_chemistry_molecular_conformation_shared.o \
./example/chemistry/example_chemistry_molecular_constitution_shared.o \
./example/chemistry/example_chemistry_molecule_complete.o \
./example/chemistry/example_chemistry_molecule_ensemble.o \
./example/chemistry/example_chemistry_molecule_environment.o \
./example/chemistry/example_chemistry_molecule_fragment_recombination.o \
./example/chemistry/example_chemistry_molecule_storage_file.o \
./example/chemistry/example_chemistry_mutate_chirality.o \
./example/chemistry/example_chemistry_mutate_fragment.o \
./example/chemistry/example_chemistry_pick_atom_random.o \
./example/chemistry/example_chemistry_possible_atom_types_for_atom.o \
./example/chemistry/example_chemistry_priority_dihedral_angles.o \
./example/chemistry/example_chemistry_reaction_complete.o \
./example/chemistry/example_chemistry_reaction_ensemble.o \
./example/chemistry/example_chemistry_reaction_search.o \
./example/chemistry/example_chemistry_reaction_structure.o \
./example/chemistry/example_chemistry_reaction_worker.o \
./example/chemistry/example_chemistry_rotamer_dihedral_bond_data.o \
./example/chemistry/example_chemistry_rotamer_library_file.o \
./example/chemistry/example_chemistry_sample_conformations.o \
./example/chemistry/example_chemistry_search_fragment_library_from_tree.o \
./example/chemistry/example_chemistry_small_molecule_fragment_isomorphism.o \
./example/chemistry/example_chemistry_small_molecule_fragment_mapping.o \
./example/chemistry/example_chemistry_small_molecule_misc_properties.o \
./example/chemistry/example_chemistry_small_molecule_qsar_storage_file.o \
./example/chemistry/example_chemistry_small_molecule_string_properties_cached.o \
./example/chemistry/example_chemistry_small_molecule_string_properties_mapped.o \
./example/chemistry/example_chemistry_small_molecule_string_properties_name.o \
./example/chemistry/example_chemistry_small_molecule_string_properties_numeric.o \
./example/chemistry/example_chemistry_small_molecule_string_properties_types.o \
./example/chemistry/example_chemistry_solvents.o \
./example/chemistry/example_chemistry_stereocenters_handler.o \
./example/chemistry/example_chemistry_sub_fragment.o \
./example/chemistry/example_chemistry_substituent_conformational.o 

CPP_DEPS += \
./example/chemistry/example_chemistry.d \
./example/chemistry/example_chemistry_aa_fragment_complete.d \
./example/chemistry/example_chemistry_atom_clash_score.d \
./example/chemistry/example_chemistry_atom_complete.d \
./example/chemistry/example_chemistry_atom_configurational_shared.d \
./example/chemistry/example_chemistry_atom_conformational_shared.d \
./example/chemistry/example_chemistry_atom_constitutional_shared.d \
./example/chemistry/example_chemistry_atom_environment.d \
./example/chemistry/example_chemistry_atom_environment_bender.d \
./example/chemistry/example_chemistry_atom_one_four_interaction_score.d \
./example/chemistry/example_chemistry_atom_type_data.d \
./example/chemistry/example_chemistry_atom_types.d \
./example/chemistry/example_chemistry_atom_vdw_score.d \
./example/chemistry/example_chemistry_atom_vector.d \
./example/chemistry/example_chemistry_bond_configurational.d \
./example/chemistry/example_chemistry_bond_conformational.d \
./example/chemistry/example_chemistry_bond_constitutional.d \
./example/chemistry/example_chemistry_bond_isometry_handler.d \
./example/chemistry/example_chemistry_bond_lengths.d \
./example/chemistry/example_chemistry_collector_valence.d \
./example/chemistry/example_chemistry_configuration_graph_converter.d \
./example/chemistry/example_chemistry_configuration_set.d \
./example/chemistry/example_chemistry_configuration_set_same_constitution.d \
./example/chemistry/example_chemistry_configurational_bond_type_data.d \
./example/chemistry/example_chemistry_configurational_bond_types.d \
./example/chemistry/example_chemistry_conformation_comparison_by_dihedral_bins.d \
./example/chemistry/example_chemistry_conformation_comparison_by_dihedrals.d \
./example/chemistry/example_chemistry_conformation_comparison_by_fragments.d \
./example/chemistry/example_chemistry_conformation_comparison_by_property.d \
./example/chemistry/example_chemistry_conformation_comparison_by_real_space_rmsd.d \
./example/chemistry/example_chemistry_conformation_comparison_by_rmsd.d \
./example/chemistry/example_chemistry_conformation_comparison_by_substructure.d \
./example/chemistry/example_chemistry_conformation_comparison_by_symmetry_rmsd.d \
./example/chemistry/example_chemistry_conformation_comparison_property_field_correlation.d \
./example/chemistry/example_chemistry_conformation_comparison_property_rmsd_x.d \
./example/chemistry/example_chemistry_conformation_comparison_psi_field.d \
./example/chemistry/example_chemistry_conformation_comparison_psi_flex_field.d \
./example/chemistry/example_chemistry_conformation_graph_converter.d \
./example/chemistry/example_chemistry_conformation_set.d \
./example/chemistry/example_chemistry_conformation_set_same_configuration.d \
./example/chemistry/example_chemistry_conformation_set_same_constitution.d \
./example/chemistry/example_chemistry_constitution_graph_converter.d \
./example/chemistry/example_chemistry_constitution_set.d \
./example/chemistry/example_chemistry_constitutional_bond_type_data.d \
./example/chemistry/example_chemistry_constitutional_bond_types.d \
./example/chemistry/example_chemistry_coulombic_score.d \
./example/chemistry/example_chemistry_cs_code.d \
./example/chemistry/example_chemistry_descriptor_to_score_adaptor.d \
./example/chemistry/example_chemistry_electron_configuration.d \
./example/chemistry/example_chemistry_element_structure_factor.d \
./example/chemistry/example_chemistry_element_type_data.d \
./example/chemistry/example_chemistry_element_types.d \
./example/chemistry/example_chemistry_fragment_alchemy.d \
./example/chemistry/example_chemistry_fragment_complete.d \
./example/chemistry/example_chemistry_fragment_configuration_shared.d \
./example/chemistry/example_chemistry_fragment_conformation_shared.d \
./example/chemistry/example_chemistry_fragment_connector.d \
./example/chemistry/example_chemistry_fragment_constitution_shared.d \
./example/chemistry/example_chemistry_fragment_cyclize.d \
./example/chemistry/example_chemistry_fragment_ensemble.d \
./example/chemistry/example_chemistry_fragment_feed_from_file.d \
./example/chemistry/example_chemistry_fragment_feed_from_stream.d \
./example/chemistry/example_chemistry_fragment_graph_marker.d \
./example/chemistry/example_chemistry_fragment_grow.d \
./example/chemistry/example_chemistry_fragment_molecule.d \
./example/chemistry/example_chemistry_fragment_probability_score.d \
./example/chemistry/example_chemistry_fragment_remove_bond.d \
./example/chemistry/example_chemistry_fragment_ring_swap.d \
./example/chemistry/example_chemistry_fragment_split_ecfp_fragments.d \
./example/chemistry/example_chemistry_fragment_split_isolate.d \
./example/chemistry/example_chemistry_fragment_split_largest_component.d \
./example/chemistry/example_chemistry_fragment_split_linear_fragments.d \
./example/chemistry/example_chemistry_fragment_split_rigid.d \
./example/chemistry/example_chemistry_fragment_split_rings.d \
./example/chemistry/example_chemistry_fragment_split_rings_with_unsaturated_substituents.d \
./example/chemistry/example_chemistry_fragment_split_scaffolds.d \
./example/chemistry/example_chemistry_fragment_split_unbridged_rings.d \
./example/chemistry/example_chemistry_fragment_swap_amide.d \
./example/chemistry/example_chemistry_has_properties.d \
./example/chemistry/example_chemistry_merge_fragment_complete.d \
./example/chemistry/example_chemistry_mol_align_by_parts.d \
./example/chemistry/example_chemistry_molecular_configuration_shared.d \
./example/chemistry/example_chemistry_molecular_conformation_shared.d \
./example/chemistry/example_chemistry_molecular_constitution_shared.d \
./example/chemistry/example_chemistry_molecule_complete.d \
./example/chemistry/example_chemistry_molecule_ensemble.d \
./example/chemistry/example_chemistry_molecule_environment.d \
./example/chemistry/example_chemistry_molecule_fragment_recombination.d \
./example/chemistry/example_chemistry_molecule_storage_file.d \
./example/chemistry/example_chemistry_mutate_chirality.d \
./example/chemistry/example_chemistry_mutate_fragment.d \
./example/chemistry/example_chemistry_pick_atom_random.d \
./example/chemistry/example_chemistry_possible_atom_types_for_atom.d \
./example/chemistry/example_chemistry_priority_dihedral_angles.d \
./example/chemistry/example_chemistry_reaction_complete.d \
./example/chemistry/example_chemistry_reaction_ensemble.d \
./example/chemistry/example_chemistry_reaction_search.d \
./example/chemistry/example_chemistry_reaction_structure.d \
./example/chemistry/example_chemistry_reaction_worker.d \
./example/chemistry/example_chemistry_rotamer_dihedral_bond_data.d \
./example/chemistry/example_chemistry_rotamer_library_file.d \
./example/chemistry/example_chemistry_sample_conformations.d \
./example/chemistry/example_chemistry_search_fragment_library_from_tree.d \
./example/chemistry/example_chemistry_small_molecule_fragment_isomorphism.d \
./example/chemistry/example_chemistry_small_molecule_fragment_mapping.d \
./example/chemistry/example_chemistry_small_molecule_misc_properties.d \
./example/chemistry/example_chemistry_small_molecule_qsar_storage_file.d \
./example/chemistry/example_chemistry_small_molecule_string_properties_cached.d \
./example/chemistry/example_chemistry_small_molecule_string_properties_mapped.d \
./example/chemistry/example_chemistry_small_molecule_string_properties_name.d \
./example/chemistry/example_chemistry_small_molecule_string_properties_numeric.d \
./example/chemistry/example_chemistry_small_molecule_string_properties_types.d \
./example/chemistry/example_chemistry_solvents.d \
./example/chemistry/example_chemistry_stereocenters_handler.d \
./example/chemistry/example_chemistry_sub_fragment.d \
./example/chemistry/example_chemistry_substituent_conformational.d 


# Each subdirectory must supply rules for building sources it contributes
example/chemistry/%.o: ../example/chemistry/%.cpp example/chemistry/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	distcc g++ -I../include -I../example -I../apps -I../extern/noarch/mysql/5.1.48/include -I../extern/noarch/mysqlpp/3.1.0/include -I../extern/noarch/bzip2/1.0.5/include -I../extern/noarch/zlib/1.2.5/include -I../extern/noarch/ati/2.5/include -O2 -Wall -c -fmessage-length=0 -Wno-deprecated -fno-pretty-templates -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


