################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
apps \
apps/descriptor \
apps/internal/biology \
apps/internal/chemistry \
apps/internal/util \
apps/model \
apps/molecule \
apps/release \
apps/restraint \
example/align \
example/apps/descriptor \
example/apps \
example/apps/internal/biology \
example/apps/internal/chemistry \
example/apps/model \
example/apps/molecule \
example/apps/release \
example/apps/restraint \
example/assemble \
example \
example/biol \
example/bzip2 \
example/chemistry \
example/cluster \
example/command \
example/contact \
example/coord \
example/crypt \
example/density \
example/descriptor \
example/find \
example/fold \
example/function \
example/graph \
example/gzip \
example/io \
example/iterate \
example/linal \
example/math \
example/mc \
example/model \
example/nmr \
example/openblas \
example/opencl \
example/opti \
example/pdb \
example/pthread \
example/quality \
example/random \
example/restraint \
example/sched \
example/score \
example/scorestat \
example/sdf \
example/signal \
example/sspred \
example/storage \
example/type \
example/util \
source/align \
source/app \
source/assemble \
source \
source/biol \
source/bzip2 \
source/chemistry \
source/cluster \
source/command \
source/contact \
source/coord \
source/crypt \
source/density \
source/descriptor \
source/find \
source/fold \
source/function \
source/graph \
source/gzip \
source/io \
source/iterate \
source/linal \
source/math \
source/mc \
source/model \
source/nmr \
source/openblas \
source/opencl \
source/opti \
source/pdb \
source/pthread \
source/quality \
source/random \
source/restraint \
source/sched \
source/score \
source/scorestat \
source/sdf \
source/signal \
source/sspred \
source/storage \
source/type \
source/util \

