176
>P1; description

--GSHMSD-MTRDGLANKALAVARTLADSPEIRQGLQK--KPQESGIQAI
AEAVRKR-NDL----LFIVVTDMQSLRYSHPEAQRIG---QPFKGDDILK
ALNGEENVAINR--GFLAQAL-------RVFTPIYDENHKQIGVVAI---
---GLE------LSRVTQQINDSR--*

>P1; description

STGFHHADHVNYSSNLNKEEILEQLLLSYEGLSDGQVNWVCNLSNASSLI
WHAYKSLAVDINWAGFYVTQASEENTLILGPFQGKVACQMIQFGKGVCGT
AASTKETQIVPDVNKYPGHIACDGETKSEIVVPIISNDGKTLGVIDIDCL
DYEGFDHVDKEFLEKLAKLINKSCVF*
