>BCL:A|PDBID|CHAIN|SEQUENCE

QAQITGRPEWIWLALGTALMGLGTLYFL-VKG--MGVSDPDAKKFYAITTLVPAIAFTMYLSMLLGYGLT
MVPFGGEQNPIYWARYADWLFTTPLLLLDLALL--VDA-DQGTILALVGADGIMIGTGLVGALTKVYSYR
FVWWAISTAAMLYILYVLFFG-FT-SKAESMRPEVA-STFKV-LRNVTVVLWSAYPVVWLIGSEGAGIV-
PLNIETLLFMVLDVSAKVGFGLILLRSRAIFGEAEAPEPS-AG-DG-AAATSD--------*

>BCL:A|PDBID|CHAIN|SEQUENCE

---MVGLTTLFW--LGAIGMLVGTLAFAWA-GRDAG-SG-E-RRYYVTLVGISGIAAVAYAVMALGVGW-
-VP-VAERT-VFVPRYIDWILTTPLIVYFLGLLAGLDSREFGIVITL-NT-VVMLA-GFAGAMVPGIE-R
YALFGMGAVAFIGLVYYL-VGPMTES-A-SQRSSGIKSLY-VRLRNLTVVLWAIYPFIWLLGPPGVALLT
P-TVDVALIVYLDLVTKVGFGFIALDA-AATLRAEHGE-SLAGVDTDTPAVADLEHHHHHH*
