>2LZM:A|PDBID|CHAIN|SEQUENCE

MNIFEMLRIDEGLRLKIY-KDTEGYYTIGIGHLLTKSPSLNAAKSELDKAIGRNCNGVITKDEAEKL-FN
-QDVDAAVRGILRNAKLKPVYDSLDAV-R-R--CALINMVFQMGETGVAGFTNSLRMLQQKRWDEAAVNL
AKSRWYNQTPNRAKRVITTFRTGTWDAYKNL*
>1UBI:A|PDBID|CHAIN|SEQUENCE

--------------MQIFVKTLTG-KTI-T--LEV-EPS-DTIENVKAK-I-QDKEG-IPPDQ-QRLIFA
GKQLEDG-R-TLSDYNIQKE-STLHLVLRLRGG-------------------------------------
-------------------------------*
